# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Page Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'
        
    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn build
      
    - name: Deploy
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: gh-pages
        repository: build
        push_options: '--force'
