# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Page Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'yarn'
        
    - name: Install Dependencies
      run: yarn

    - name: Build
      run: yarn build
      
    - name: Deploy
      run: |
        git config --global user.name 'Alan Luo'
        git config --global user.email 'iltc@users.noreply.github.com'
        git remote set-url origin https://${github_token}:x-oauth-basic@github.com/${repository}
        yarn gh-pages -d build
      env:
        github_token: ${{ github.token }}
        repository: ${{ github.repository }}
